<?php

/**
 * @file
 * Module file for autoshortqr.
 */

use Drupal\Core\Render\BubbleableMetadata;
use Drupal\taxonomy\Entity\Vocabulary;
use Drupal\node\Entity\NodeType;
use Drupal\Core\Config\Entity\ThirdPartySettingsInterface;
use Drupal\Core\Entity\EntityFormInterface;
use Drupal\autoshortqr\Controller\CodeController;
use Drupal\Core\Url;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\autoshortqr\UserThirdpartyWrapper;
use Drupal\autoshortqr\RedirectThirdpartyWrapper;

/**
 * Implements hook_form_node_type_form_alter().
 */
function autoshortqr_form_node_type_form_alter(array &$form, FormStateInterface $form_state) {
  if ($form_state->getFormObject() instanceof EntityFormInterface) {
    /** @var \Drupal\Core\Entity\EntityFormInterface $formObject */
    $formObject = $form_state->getFormObject();
    /** @var \Drupal\node\NodeTypeInterface $type */
    $type = $formObject->getEntity();
    _autoshortqr_build_form($type, $form, $form_state);
  }
}

/**
 * Implements hook_form_user_admin_settings_alter().
 */
function autoshortqr_form_user_admin_settings_alter(array &$form, FormStateInterface $form_state) {
  // _autoshortqr_build_form($type, $form, $form_state);
  $type = new UserThirdpartyWrapper();
  _autoshortqr_build_form($type, $form, $form_state);
}

/**
 * Implements hook_form_taxonomy_vocabulary_form_alter().
 */
function autoshortqr_form_taxonomy_vocabulary_form_alter(array &$form, FormStateInterface $form_state) {
  if ($form_state->getFormObject() instanceof EntityFormInterface) {
    /** @var \Drupal\Core\Entity\EntityFormInterface $formObject */
    $formObject = $form_state->getFormObject();
    /** @var \Drupal\node\NodeTypeInterface $type */
    $type = $formObject->getEntity();
    _autoshortqr_build_form($type, $form, $form_state);
  }
}

/**
 * Implements hook_form_redirect_admin_settings_alter().
 */
function autoshortqr_form_redirect_settings_form_alter(array &$form, FormStateInterface $form_state) {
  $type = new RedirectThirdpartyWrapper();
  _autoshortqr_build_form($type, $form, $form_state);
}

/**
 * Implements hook_entity_base_field_info().
 */
function autoshortqr_entity_bundle_field_info(EntityTypeInterface $entity_type, $bundle, array $base_field_definitions) {
  if ($entity_type->id() == 'node') {
    $type = NodeType::load($bundle);
  }
  if ($entity_type->id() == 'taxonomy_term') {
    $type = Vocabulary::load($bundle);
  }
  if ($entity_type->id() == 'user') {
    $type = new UserThirdpartyWrapper();
  }
  if ($entity_type->id() == 'redirect') {
    $type = new RedirectThirdpartyWrapper();
  }
  if (!empty($type)) {
    if ($type->getThirdPartySetting('autoshortqr', 'qr_enable')) {

      // Add the autocode field.
      $fields['autoshortqr'] = BaseFieldDefinition::create('autoshortqr')
        ->setName('autoshortqr')
        ->setLabel(t('Autocode field'))
        ->setComputed(TRUE)
        ->setClass('\Drupal\autoshortqr\AutoCodeLinkList')
        ->setCardinality(1)
        ->setDisplayConfigurable('view', TRUE)
        ->setDisplayOptions('view', [
          'label' => 'hidden',
          'weight' => -5,
          'region' => 'hidden',
        ]);
    }
    if ($type->getThirdPartySetting('autoshortqr', 'short_enable')) {
      // Add the autocode field.
      $fields['autoshortqr_short_link'] = BaseFieldDefinition::create('autoshortqr_shortlink')
        ->setName('autoshortqr_short_link')
        ->setLabel(t('Short link'))
        ->setComputed(TRUE)
        ->setClass('\Drupal\autoshortqr\AutoCodeLinkList')
        ->setCardinality(1)
        ->setDisplayConfigurable('view', TRUE)
        ->setDisplayOptions('view', [
          'label' => 'hidden',
          'weight' => -5,
          'region' => 'hidden',
        ]);
      return $fields;
    }
  }
}

/**
 * Implements hook_form_node_form_alter().
 */
function autoshortqr_form_node_form_alter(&$form, &$form_state, $form_id) {

  $entity = $form_state->getFormObject()->getEntity();
  $settings = $entity->type->entity->getThirdPartySettings('autoshortqr');
  _autoshortqr_add_autocode_output($form, $entity, $settings);
}

/**
 * Implements hook_form_user_form_alter().
 */
function autoshortqr_form_user_form_alter(&$form, &$form_state, $form_id) {

  $entity = $form_state->getFormObject()->getEntity();
  $settings = (new UserThirdpartyWrapper())->getThirdPartySettings('autoshortqr');
  _autoshortqr_add_autocode_output($form, $entity, $settings);
}

/**
 * Implements hook_form_redirect_form_alter().
 */
function autoshortqr_form_redirect_redirect_edit_form_alter(&$form, &$form_state, $form_id) {

  $entity = $form_state->getFormObject()->getEntity();
  $settings = (new RedirectThirdpartyWrapper())->getThirdPartySettings('autoshortqr');
  _autoshortqr_add_autocode_output($form, $entity, $settings);
}

/**
 * Implements hook_form_taxonomy_term_form_alter().
 */
function autoshortqr_form_taxonomy_term_form_alter(&$form, &$form_state, $form_id) {
  $entity = $form_state->getFormObject()->getEntity();
  $settings = Vocabulary::load($entity->bundle())->getThirdPartySettings('autoshortqr');
  _autoshortqr_add_autocode_output($form, $entity, $settings);
}

/**
 * Implements hook_field_formatter_info_alter().
 */
function autoshortqr_field_formatter_info_alter(array &$info) {
  $info['link']['field_types'][] = 'autoshortqr_shortlink';
}

/**
 * Implements hook_field_widget_info_alter().
 */
function autoshortqr_field_widget_info_alter(array &$info) {
  $info['link_default']['field_types'][] = 'autoshortqr_shortlink';
}

/**
 * Implements hook_views_data().
 */
function autoshortqr_views_data() {
  $data = [];
  $definition = [
    'autoshortqr' => [
      'title' => t('Qr code'),
      'help' => t('Qr code to the entity.'),
      'field' => [
        'id' => 'autoshortqr',
      ],
    ],
    'autoshortqr_short_link' => [
      'title' => t('Short link'),
      'help' => t('Short link to the entity.'),
      'field' => [
        'id' => 'autoshortqr_short_link',
      ],
    ],
  ];
  $entityTypes = ['node', 'user', 'term', 'redirect'];
  foreach ($entityTypes as $typeId) {
    $type = \Drupal::entityTypeManager()->getDefinition($typeId, FALSE);
    if (!empty($type)) {
      if (!empty($type->getDataTable())) {
        $data[$type->getDataTable()] = $definition;
      } else {
        $data[$type->getBaseTable()] = $definition;
      }
    }
  }
  return $data;
}

/**
 * Implements hook_token_info().
 */
function autoshortqr_token_info() {
  $autocodeTokens = [
    'iqac_short_link' =>
    [
      'name' => t('Autocode Short url'),
      'description' => t('Short url of the entity.'),
    ],
    'iqac_qr_link' =>
    [
      'name' => t('Autocode QR code url'),
      'description' => t('QR code url of the entity.'),
    ],
    'iqac_qr_download_link' =>
    [
      'name' => t('Autocode QR code download url'),
      'description' => t('QR code download url of the entity.'),
    ],
  ];
  $info = [
    'tokens' =>
    [
      'node' => $autocodeTokens,
      'term' => $autocodeTokens,
      'user' => $autocodeTokens,
    ],
  ];

  $type = \Drupal::entityTypeManager()->getDefinition('redirect', FALSE);
  if (!empty($type)) {
    $info['tokens']['redirect'] = $autocodeTokens;
  }

  return $info;
}

/**
 * Implements hook_tokens().
 */
function autoshortqr_tokens($type, $tokens, array $data, array $options, BubbleableMetadata $bubbleable_metadata) {
  $keys = array_intersect(
    ['iqac_short_link', 'iqac_qr_link', 'iqac_qr_download_link'],
    array_keys($tokens)
  );
  if (empty($keys)) {
    return;
  }
  $replacements = [];
  $entity = NULL;
  $entityType = NULL;
  $prefix = '';
  switch ($type) {
    case 'node':
      if (!empty($data[$type])) {
        $entity = $data[$type];
        $entity = \Drupal::entityTypeManager()->getStorage($type)->loadUnchanged($entity->id());
        $entityType = $entity->type->entity;
        $prefix = 'tc';
      }
      break;

    case 'term':
      if (!empty($data[$type])) {
        $entity = $data[$type];
        $entity = \Drupal::entityTypeManager()->getStorage($type)->loadUnchanged($entity->id());
        $entityType = Vocabulary::load($entity->bundle());
        $prefix = 'tc';
      }
      break;

    case 'user':
      if (!empty($data[$type])) {
        $entity = $data[$type];
        $entity = \Drupal::entityTypeManager()->getStorage($type)->loadUnchanged($entity->id());
        $entityType = new UserThirdpartyWrapper();
        $prefix = 'uc';
      }
      break;

    case 'redirect':
      if (!empty($data[$type])) {
        $entity = $data[$type];
        $entity = \Drupal::entityTypeManager()->getStorage($type)->loadUnchanged($entity->id());
        $entityType = new RedirectThirdpartyWrapper();
        $prefix = 'rc';
      }
      break;
  }
  if (!empty($entity) && !empty($entityType)) {
    foreach ($tokens as $name => $original) {
      // Find the desired token by name.
      switch ($name) {
        case 'iqac_short_link':
          if ($entityType->getThirdpartySetting('autoshortqr', 'short_enable', FALSE)) {
            $replacements[$original] = $entity->autoshortqr_short_link->uri;
          }
          break;

        case 'iqac_qr_link':
          if ($entityType->getThirdpartySetting('autoshortqr', 'qr_enable', FALSE)) {
            $replacements[$original] = $entity->autoshortqr->uri;
          }
          break;

        case 'iqac_qr_download_link':
          if ($entityType->getThirdpartySetting('autoshortqr', 'qr_enable', FALSE)) {
            $host = $entityType->getThirdPartySetting('autoshortqr', 'qr_base_domain', \Drupal::request()->getSchemeAndHttpHost());
            $url = $host . '/autoshortqr/' . $prefix . '/' . base_convert($entity->id(), 10, 36);
            $replacements[$original] = $url;
          }
          break;
      }
    }
  }

  // Return the replacements.
  return $replacements;
}

/**
 * Helper function to build the entity settings form.
 */
function _autoshortqr_build_form(ThirdPartySettingsInterface $type, array &$form, FormStateInterface $form_state) {

  $form['autoshortqr'] = [
    '#type' => 'details',
    '#title' => t('Autocode'),
    '#weight' => 35,
    '#group' => 'additional_settings',
  ];

  $form['autoshortqr']['qr_code'] = [
    '#type' => 'details',
    '#title' => t('QR code'),
    '#weight' => 0,
    '#open' => TRUE,
  ];
  $form['autoshortqr']['qr_code']['autoshortqr_qr_enable'] = [
    '#type' => 'checkbox',
    '#title' => t('Enable autocode on this type'),
    '#default_value' => $type->getThirdPartySetting('autoshortqr', 'qr_enable', FALSE),

  ];
  $form['autoshortqr']['qr_code']['autoshortqr_qr_base_domain'] = [
    '#type' => 'url',
    '#title' => t('Base domain'),
    '#description' => t('Set the domain to use for link generation. Defaults to active url on qr code view.'),
    '#url' => $type->getThirdPartySetting('autoshortqr', 'qr_base_domain', ''),
    '#states' => [
      'visible' => [
        ':input[name="autoshortqr_qr_enable"]' => ['checked' => TRUE],
      ],
    ],
  ];

  $form['autoshortqr']['qr_code']['autoshortqr_qr_show'] = [
    '#type' => 'checkbox',
    '#title' => t('Show the qr code on edit form'),
    '#description' => t('Show the qr code on edit form'),
    '#default_value' => $type->getThirdPartySetting('autoshortqr', 'qr_show', TRUE),
    '#states' => [
      'visible' => [
        ':input[name="autoshortqr_qr_enable"]' => ['checked' => TRUE],
      ],
    ],
  ];
  $form['autoshortqr']['qr_code']['autoshortqr_qr_show_url'] = [
    '#type' => 'checkbox',
    '#title' => t('Show url on edit form'),
    '#description' => t('Show url on edit form'),
    '#default_value' => $type->getThirdPartySetting('autoshortqr', 'qr_show_url', FALSE),
    '#states' => [
      'visible' => [
        ':input[name="autoshortqr_qr_enable"]' => ['checked' => TRUE],
      ],
    ],
  ];

  $form['autoshortqr']['qr_code'] += _autoshortqr_get_utm_fields('qr', $type);

  $form['autoshortqr']['short_link'] = [
    '#type' => 'details',
    '#title' => t('Short url'),
    '#weight' => 0,
    '#open' => TRUE,
  ];
  $form['autoshortqr']['short_link']['autoshortqr_short_enable'] = [
    '#type' => 'checkbox',
    '#title' => t('Enable short url on this type'),
    '#default_value' => $type->getThirdPartySetting('autoshortqr', 'short_enable', FALSE),
  ];
  $form['autoshortqr']['short_link']['autoshortqr_short_base_domain'] = [
    '#type' => 'url',
    '#title' => t('Set base domain'),
    '#description' => t('Set the domain to use for link generation. Defaults to active url on short link view.'),
    '#url' => $type->getThirdPartySetting('autoshortqr', 'short_base_domain', ''),
    '#states' => [
      'visible' => [
        ':input[name="autoshortqr_short_enable"]' => ['checked' => TRUE],
      ],
    ],
  ];

  $form['autoshortqr']['short_link']['autoshortqr_short_show_url'] = [
    '#type' => 'checkbox',
    '#title' => t('Show url on edit form'),
    '#description' => t('Show url on edit form'),
    '#default_value' => $type->getThirdPartySetting('autoshortqr', 'short_show_url', TRUE),
    '#states' => [
      'visible' => [
        ':input[name="autoshortqr_short_enable"]' => ['checked' => TRUE],
      ],
    ],
  ];

  $form['autoshortqr']['short_link'] += _autoshortqr_get_utm_fields('short', $type);

  if (
    method_exists($type, 'getEntityTypeId') &&
      (
        $type->getEntityTypeId() == 'user'
        ||
        $type->getEntityTypeId() == 'redirect'
      )
    ) {
    foreach (array_keys($form['actions']) as $action) {
      if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
        $form['actions'][$action]['#submit'][] = '_autoshortqr_form_submit_' . $type->getEntityTypeId();
      }
    }
  }
  else {
    $form['#entity_builders'][] = '_autoshortqr_form_type_form_builder';
  }

}

/**
 * Helper to include the utm fields for the form.
 */
function _autoshortqr_get_utm_fields($target, ThirdPartySettingsInterface $type) {
  $fields = [];

  $fields['utm_params'] = [
    '#type' => 'details',
    '#title' => t('UTM parameters'),
    '#open' => TRUE,
    '#states' => [
      'visible' => [
        ':input[name="autoshortqr_' . $target . '_enable"]' => ['checked' => TRUE],
      ],
    ],
  ];

  foreach (CodeController::UTM_VARS as $utmVar) {
    $fields['utm_params']['autoshortqr_' . $target . '_' . $utmVar] = [
      '#type' => 'textfield',
      '#title' => $utmVar,
      '#default_value' => $type->getThirdPartySetting('autoshortqr', $target . '_' . $utmVar, ''),
    ];
  }
  if (method_exists($type, 'getEntityTypeId')) {
    $fields['utm_params']['token_tree'] = [
      '#theme' => 'token_tree_link',
      '#token_types' => [str_replace('_type', '', $type->getEntityTypeId())],
      '#show_restricted' => TRUE,
    ];
  }
  return $fields;
}

/**
 * Submit function for account settings form.
 */
function _autoshortqr_form_submit_user(array $form, FormStateInterface $form_state) {
  $type = new UserThirdpartyWrapper();
  _autoshortqr_form_type_form_builder(NULL, $type, $form, $form_state);
}

/**
 * Submit function for redirect settings form.
 */
function _autoshortqr_form_submit_redirect(array $form, FormStateInterface $form_state) {
  $type = new RedirectThirdpartyWrapper();
  _autoshortqr_form_type_form_builder(NULL, $type, $form, $form_state);
}

/**
 * Submit function for node and term type form.
 */
function _autoshortqr_form_type_form_builder($entity_type, ThirdPartySettingsInterface $type, &$form, FormStateInterface $form_state) {
  // QR code.
  $type->setThirdPartySetting('autoshortqr', 'qr_enable', $form_state->getValue('autoshortqr_qr_enable'));
  $baseDomain = $form_state->getValue('autoshortqr_qr_base_domain');
  if (empty($baseDomain)) {
    $type->unsetThirdPartySetting('autoshortqr', 'qr_base_domain');
  }
  else {
    $type->setThirdPartySetting('autoshortqr', 'qr_base_domain', $baseDomain);
  }
  $type->setThirdPartySetting('autoshortqr', 'qr_show', $form_state->getValue('autoshortqr_qr_show'));
  $type->setThirdPartySetting('autoshortqr', 'qr_show_url', $form_state->getValue('autoshortqr_qr_show_url'));
  _autoshortqr_save_utm_parameters('qr', $type, $form_state);

  // Short url.
  $type->setThirdPartySetting('autoshortqr', 'short_enable', $form_state->getValue('autoshortqr_short_enable'));
  $baseDomain = $form_state->getValue('autoshortqr_short_base_domain');
  if (empty($baseDomain)) {
    $type->unsetThirdPartySetting('autoshortqr', 'short_base_domain');
  }
  else {
    $type->setThirdPartySetting('autoshortqr', 'short_base_domain', $baseDomain);
  }
  $type->setThirdPartySetting('autoshortqr', 'short_show_url', $form_state->getValue('autoshortqr_short_show_url'));
  _autoshortqr_save_utm_parameters('short', $type, $form_state);
}

/**
 * Helper to save utm parameters.
 */
function _autoshortqr_save_utm_parameters($target, ThirdPartySettingsInterface $type, FormStateInterface $form_state) {
  foreach (CodeController::UTM_VARS as $utmVar) {
    $value = $form_state->getValue('autoshortqr_' . $target . '_' . $utmVar);
    $type->setThirdPartySetting('autoshortqr', $target . '_' . $utmVar, $value);
  }
}

/**
 * Helper to add autocode output to entity edit forms.
 */
function _autoshortqr_add_autocode_output(&$form, $entity, $settings) {
  if ($entity->isNew()) {
    return;
  }
  if (!empty($settings['qr_enable'])) {
    $prefix = 'nc';

    if ($entity->getEntityTypeId() == 'taxonomy_term') {
      $prefix = 'tc';
    }

    if ($entity->getEntityTypeId() == 'user') {
      $prefix = 'uc';
    }

    if ($entity->getEntityTypeId() == 'redirect') {
      $prefix = 'rc';
    }

    $form['meta']['autoshortqr_qr_container'] = [
      '#type' => 'fieldset',
      '#title' => t('QR Code'),
      '#weight' => 100,
    ];
    if ($settings['qr_show']) {
      $form['meta']['autoshortqr_qr_container']['autoshortqr'] = $entity->autoshortqr->view([
        'type' => 'autoshortqr',
        'label' => '',
        'settings' => [
          'height' => 200,
          'width' => 200,
        ],
      ]);
      $form['meta']['autoshortqr_qr_container']['autoshortqr']['#label_display'] = 'hidden';
      $form['meta']['autoshortqr_qr_container']['autoshortqr']['#prefix'] = '<a href="/autoshortqr/' . $prefix . '/' . base_convert($entity->id(), 10, 36) . '" target="_blank">';
      $form['meta']['autoshortqr_qr_container']['autoshortqr']['#suffix'] = '</a>';
    }
    if ($settings['qr_show_url']) {
      $url = Url::fromUri($entity->autoshortqr->uri);
      $form['meta']['autoshortqr_qr_container']['autoshortqr_url'] = [
        '#type' => 'link',
        '#url' => $url,
        '#title' => $url->toString(),
        '#attributes' => ['target' => '_blank'],
      ];
    }
  }
  if (!empty($settings['short_enable'])) {
    if ($settings['short_show_url']) {
      $url = Url::fromUri($entity->autoshortqr_short_link->uri);
      $form['meta']['autoshortqr_short_link_container'] = [
        '#type' => 'fieldset',
        '#title' => t('Short URL'),
        '#weight' => 201,
      ];
      $form['meta']['autoshortqr_short_link_container']['autoshortqr_short_link'] = [
        '#type' => 'link',
        '#url' => $url,
        '#title' => $url->toString(),
        '#attributes' => ['target' => '_blank'],
      ];
    }
  }
}
